services:
  sma-sbfspot-runtime:
    image: ghcr.io/johannes667/sma-sbfspot-runtime:latest
    build: .
    container_name: SMA-SBFspot-Runtime
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sma-sbfspot:/config
      - /mnt/user/appdata/sma-sbfspot/data:/data
      - /var/run/dbus:/var/run/dbus
    environment:
      INTERVAL: "300"
      WEB_PORT: "8088"
      MQTT_ENABLE: "true"
      MQTT_HOST: "192.168.2.115"
      MQTT_PORT: "1883"
      MQTT_USER: "sbfspot"
      MQTT_PASSWORD: ""
      MQTT_BASE_TOPIC: "sma/sbfspot"
      HA_DISCOVERY: "true"
      DEVICE_NAME: "SMA Wechselrichter Amann"
      DEVICE_ID: "sma_sbfspot_amann"
