import os
CONFIG_DIR=os.getenv('CONFIG_DIR','/config')
DATA_DIR=os.getenv('DATA_DIR','/data')
SBFSPOT_CFG=os.getenv('SBFSPOT_CFG',f'{CONFIG_DIR}/SBFspot.cfg')
INTERVAL=int(os.getenv('INTERVAL','300'))
WEB_PORT=int(os.getenv('WEB_PORT','8088'))
MQTT_ENABLE=os.getenv('MQTT_ENABLE','true').lower() in ('1','true','yes','on')
MQTT_HOST=os.getenv('MQTT_HOST','127.0.0.1')
MQTT_PORT=int(os.getenv('MQTT_PORT','1883'))
MQTT_USER=os.getenv('MQTT_USER','')
MQTT_PASSWORD=os.getenv('MQTT_PASSWORD','')
MQTT_BASE_TOPIC=os.getenv('MQTT_BASE_TOPIC','sma/sbfspot').strip('/')
MQTT_RETAIN=os.getenv('MQTT_RETAIN','true').lower() in ('1','true','yes','on')
HA_DISCOVERY=os.getenv('HA_DISCOVERY','true').lower() in ('1','true','yes','on')
HA_DISCOVERY_PREFIX=os.getenv('HA_DISCOVERY_PREFIX','homeassistant').strip('/')
DEVICE_NAME=os.getenv('DEVICE_NAME','SMA Wechselrichter')
DEVICE_ID=os.getenv('DEVICE_ID','sma_sbfspot').lower().replace(' ','_')
STATE_FILE=f'{DATA_DIR}/state.json'
DB_FILE=f'{DATA_DIR}/history.sqlite3'
